esphome:
  name: central-heating-tank

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "pNSzDLfNQHhE9itAQ9gfXhufHhaSdELBeM4Qjg04LqI="

ota:
  password: "3ede5cbefcd3963d4b5ab4907cf75540"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Central-Heating-Tank"
    password: "zeFdB8ijdxma"

captive_portal:

switch:
  - platform: gpio
    name: "Central Tank Heater 1"
    id: sw_central_tank_heater1
    pin:
      number: D1
      inverted: true    
  - platform: gpio
    name: "Central Tank Heater 2"
    id: sw_central_tank_heater2
    pin:
      number: D3
      inverted: true
  - platform: gpio
    name: "Central Tank Heater 3"
    id: sw_central_tank_heater3
    pin:
      number: D5
      inverted: true       

dallas:
  - pin: D2

sensor:
  - platform: dallas
    address: 0x74020491770cfe28
    name: "Central Heating Tank Top Temperature"
    id: cht_top_temperature
    on_value_range:
      - above: 85.0
        then:
          - script.execute: cht_heaters_turn_off
  - platform: dallas
    address: 0xe6020d9177aaa628
    name: "Central Heating Tank Bottom Temperature"
    on_value_range:
      - below: 8.0
        then:
          - switch.turn_on: sw_central_tank_heater2
time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      # Cron syntax, at every 7th minute past every hour from 0 through 4 and 23.
      - cron: '* /7 0-4,23 * * *'
        then:
          - if:
              condition:
                and:
                  - switch.is_off: sw_central_tank_heater1
                  - sensor.in_range:
                      id: cht_top_temperature
                      below: 40.0
              then:
                - script.execute: cht_heaters_turn_on
          - if:
              condition:
                and:
                  - switch.is_on: sw_central_tank_heater1
                  - sensor.in_range:
                      id: cht_top_temperature
                      above: 80.0
              then:
                - script.execute: cht_heaters_turn_off      

      # Cron syntax, at every 7th minute past hour 5 and 6.
      - cron: '* /7 5-6 * * *'
        then:
          - if:
              condition:
                and:
                  - switch.is_off: sw_central_tank_heater1
                  - sensor.in_range:
                      id: cht_top_temperature
                      below: 75.0
              then:
                - script.execute: cht_heaters_turn_on
          - if:
              condition:
                and:
                  - switch.is_on: sw_central_tank_heater1
                  - sensor.in_range:
                      id: cht_top_temperature
                      above: 80.0
              then:
                - script.execute: cht_heaters_turn_off

      # 6:58:00
      - seconds: 0
        minutes: 58
        hours: 6
        then:
          - script.execute: cht_heaters_turn_off

script:
  - id: cht_heaters_turn_on
    then:
      - switch.turn_on: sw_central_tank_heater1
      - delay: 500ms
      - switch.turn_on: sw_central_tank_heater2
      - delay: 500ms
      - switch.turn_on: sw_central_tank_heater3

  - id: cht_heaters_turn_off
    then:
      - switch.turn_off: sw_central_tank_heater1
      - delay: 500ms
      - switch.turn_off: sw_central_tank_heater2
      - delay: 500ms
      - switch.turn_off: sw_central_tank_heater3

