esphome:
  name: watering
  friendly_name: watering

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "krc92s2maLttpcUfYjrhid4TsjPkW0QP2fBbNXp9l0o="

ota:
  password: "7b25d21e66b4681b31137bfb5a5e24c4"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Watering Fallback Hotspot"
    password: "sXuUC0LjqSI5"

captive_portal:

switch:
  - platform: gpio
    name: "Gryadky"
    id: sw_watering_beds
    pin: D1
  - platform: gpio
    name: "Gorod"
    id: sw_watering_vegetable_garden
    pin: D2
  - platform: gpio
    name: "Gazon"
    id: sw_watering_lawn
    pin: D3
  - platform: gpio
    name: "Klumby"
    id: sw_watering_flower_beds
    pin: D4
  - platform: gpio
    name: "Dereva"
    id: sw_watering_trees
    pin: D5
  - platform: gpio
    name: "Fontan"
    id: sw_watering_fountain
    pin: D6
  - platform: gpio
    name: "FontanNabirVody"
    id: sw_watering_fountain_set_of_water
    pin: D7
  - platform: gpio
    name: "WaterForSystem"
    id: sw_watering_tanker_set_of_water
    pin: D8

